package com.klasha.android.model

import com.google.gson.annotations.SerializedName
import java.util.*

data class Card (
    val number: String,
    val expiryMonth: Int,
    val expiryYear: Int,
    val cvv: Int,
    val name: String = ""
)

data class MobileMoney(
    val voucher: String,
    val network: Network
)

data class Charge (
    val amount: Double,
    val email: String,
    val fullName: String,
    val card: Card?,
    val mobileMoney: MobileMoney? = null,
    val phone: String = "",
    val transactionReference: String = UUID.randomUUID().toString())

data class BankTransferResp(
    @SerializedName("transfer_reference")
    val transferReference: String,
    @SerializedName("transfer_account")
    val transferAccount: String,
    @SerializedName("transfer_bank")
    val transferBank: String,
    @SerializedName("account_expiration")
    val accountExpiration: String,
    @SerializedName("transfer_note")
    val transferMode: String,
    @SerializedName("transfer_amount")
    val transferAmount: Double,
    val mode: String
)

enum class Currency {
    AFN, ALL, DZD, AOA, ARS, AMD, AWG, AZM, BSD, BHD, BDT, BBD, BYR, BZD, BMD, BAM, BWP, BRL, BGN,
    BIF, KHR, CAD, CVE, KYD, CLP, CNY, COP, KMF, CDF, CRC, HRK, CUP, CYP, CZK, DJF, DOP, EGP, ERN,
    EEK, ETB, FJD, XAF, GMD, GEL, GHS, GIP, DKK, GTQ, GNF, GYD, HTG, HNL, HKD, HUF, ISK, INR, IDR,
    IRR, IQD, ILS, JMD, JPY, JOD, KZT, KES, KWD, KGS, LVL, LBP, LRD, LTL, MOP, MWK, MYR, MVR, MTL,
    MRO, MUR, MXN, MXV, MNT, MZM, MMK, NPR, NIO, NGN, OMR, PKR, PAB, PGK, PYG, PEN, PHP, PLN, QAR,
    ROL, RWF, SHP, XCD, WST, STD, SAR, SCR, SLL, SGD, SKK, SIT, SBD, SOS, ZAR, EUR, LKR, SDD, SRD,
    NOK, SZL, SEK, CHF, SYP, TWD, TJS, TZS, THB, XOF, NZD, TOP, TTD, TND, TRL, TMM, AUD, UGX, UAH,
    AED, GBP, USD, UYU, UZS, VUV, VEB, VND, XPF, MAD, YER, ZMK, ZWD,
}

enum class Network{
    MTN
}

internal enum class PaymentType{
    card
}

internal enum class MPESAOption{
    mpesa
}

enum class CountryCode {
    AF, AL, DZ, AS, AD, AO, AI, AG, AR, AM, AW, AU, AT, AZ, BS, BH, BD, BB, BY, BE, BZ, BJ, BM,
    BA, BW, BV, BR, BG, BF, BI, KH, CM, CA, CV, KY, CF, TD, CL, CN, CX, CO, KM, CD, CK, CR, CI,
    HR, CU, CY, CZ, DK, DJ, DM, DO, EC, EG, SV, GQ, ER, EE, ET, FO, FJ, FI, FR, GF, PF, TF, GA,
    GM, GE, DE, GH, GI, GR, GL, GD, GP, GU, GT, GN, GW, GY, HT, HN, HK, HU, IS, IN, ID, IR, IQ,
    IE, IL, IT, JM, JP, JO, KZ, KE, KI, KW, KG, LV, LB, LR, LI, LT, LU, MO, MW, MY, MV, ML, MT,
    MH, MQ, MR, MU, YT, MX, FM, MC, MN, MS, MA, MZ, MM, NA, NR, NP, NL, NC, NZ, NI, NE, NG, NU,
    NF, MP, NO, OM, PK, PW, PA, PG, PY, PE, PH, PN, PL, PT, PR, QA, RE, RO, RW, SH, KN, LC, PM,
    VC, WS, SM, ST, SA, SN, SC, SL, SG, SK, SI, SB, SO, ZA, ES, LK, SD, SR, SJ, SZ, SE, CH, SY,
    TW, TJ, TZ, TH, TL, TG, TK, TO, TT, TN, TR, TM, TC, TV, UG, UA, AE, GB, US, UY, UZ, VU, VE,
    VN, WF, EH, YE, ZM, ZW,
}

enum class Country(val countryCode: CountryCode, val currency: Currency) {
    AFGHANISTAN (CountryCode.AF, Currency.AFN),
    ALBANIA (CountryCode.AL, Currency.ALL),
    ALGERIA (CountryCode.DZ, Currency.DZD),
    AMERICAN_SAMOA (CountryCode.AS, Currency.USD),
    ANDORRA (CountryCode.AD, Currency.EUR),
    ANGOLA (CountryCode.AO, Currency.AOA),
    ANGUILLA (CountryCode.AI, Currency.XCD),
    ANTIGUA_AND_BARBUDA (CountryCode.AG, Currency.XCD),
    ARGENTINA (CountryCode.AR, Currency.ARS),
    ARMENIA (CountryCode.AM, Currency.AMD),
    ARUBA (CountryCode.AW, Currency.AWG),
    AUSTRALIA (CountryCode.AU, Currency.AUD),
    AUSTRIA (CountryCode.AT, Currency.EUR),
    AZERBAIJAN (CountryCode.AZ, Currency.AZM),
    BAHAMAS (CountryCode.BS, Currency.BSD),
    BAHRAIN (CountryCode.BH, Currency.BHD),
    BANGLADESH (CountryCode.BD, Currency.BDT),
    BARBADOS (CountryCode.BB, Currency.BBD),
    BELARUS (CountryCode.BY, Currency.BYR),
    BELGIUM (CountryCode.BE, Currency.EUR),
    BELIZE (CountryCode.BZ, Currency.BZD),
    BENIN (CountryCode.BJ, Currency.XOF),
    BERMUDA (CountryCode.BM, Currency.BMD),
    BOSNIA_AND_HERZEGOVINA (CountryCode.BA, Currency.BAM),
    BOTSWANA (CountryCode.BW, Currency.BWP),
    BOUVET_ISLAND (CountryCode.BV, Currency.NOK),
    BRAZIL (CountryCode.BR, Currency.BRL),
    BULGARIA (CountryCode.BG, Currency.BGN),
    BURKINA_FASO (CountryCode.BF, Currency.XOF),
    BURUNDI (CountryCode.BI, Currency.BIF),
    CAMBODIA (CountryCode.KH, Currency.KHR),
    CAMEROON (CountryCode.CM, Currency.XAF),
    CANADA (CountryCode.CA, Currency.CAD),
    CAPE_VERDE (CountryCode.CV, Currency.CVE),
    CAYMAN_ISLANDS (CountryCode.KY, Currency.KYD),
    CENTRAL_AFRICAN_REPUBLIC (CountryCode.CF, Currency.XAF),
    CHAD (CountryCode.TD, Currency.XAF),
    CHILE (CountryCode.CL, Currency.CLP),
    CHINA (CountryCode.CN, Currency.CNY),
    CHRISTMAS_ISLAND (CountryCode.CX, Currency.AUD),
    COLOMBIA (CountryCode.CO, Currency.COP),
    COMOROS (CountryCode.KM, Currency.KMF),
    CONGO (CountryCode.CD, Currency.CDF),
    COOK_ISLANDS (CountryCode.CK, Currency.NZD),
    COSTA_RICA (CountryCode.CR, Currency.CRC),
    COTE_DIVOIRE (CountryCode.CI, Currency.XOF),
    CROATIA (CountryCode.HR, Currency.HRK),
    CUBA (CountryCode.CU, Currency.CUP),
    CYPRUS (CountryCode.CY, Currency.CYP),
    CZECH_REPUBLIC (CountryCode.CZ, Currency.CZK),
    DENMARK (CountryCode.DK, Currency.DKK),
    DJIBOUTI (CountryCode.DJ, Currency.DJF),
    DOMINICA (CountryCode.DM, Currency.XCD),
    DOMINICAN_REPUBLIC (CountryCode.DO, Currency.DOP),
    ECUADOR (CountryCode.EC, Currency.USD),
    EGYPT (CountryCode.EG, Currency.EGP),
    EL_SALVADOR (CountryCode.SV, Currency.USD),
    EQUATORIAL_GUINEA (CountryCode.GQ, Currency.XAF),
    ERITREA (CountryCode.ER, Currency.ERN),
    ESTONIA (CountryCode.EE, Currency.EEK),
    ETHIOPIA (CountryCode.ET, Currency.ETB),
    FAROE_ISLANDS (CountryCode.FO, Currency.DKK),
    FIJI (CountryCode.FJ, Currency.FJD),
    FINLAND (CountryCode.FI, Currency.EUR),
    FRANCE (CountryCode.FR, Currency.EUR),
    FRENCH_GUIANA (CountryCode.GF, Currency.EUR),
    FRENCH_POLYNESIA (CountryCode.PF, Currency.XPF),
    FRENCH_SOUTHERN_TERRITORIES (CountryCode.TF, Currency.EUR),
    GABON (CountryCode.GA, Currency.XAF),
    GAMBIA (CountryCode.GM, Currency.GMD),
    GEORGIA (CountryCode.GE, Currency.GEL),
    GERMANY (CountryCode.DE, Currency.EUR),
    GHANA (CountryCode.GH, Currency.GHS),
    GIBRALTAR (CountryCode.GI, Currency.GIP),
    GREECE (CountryCode.GR, Currency.EUR),
    GREENLAND (CountryCode.GL, Currency.DKK),
    GRENADA (CountryCode.GD, Currency.XCD),
    GUADELOUPE (CountryCode.GP, Currency.EUR),
    GUAM (CountryCode.GU, Currency.USD),
    GUATEMALA (CountryCode.GT, Currency.GTQ),
    GUINEA (CountryCode.GN, Currency.GNF),
    GUINEA_BISSAU (CountryCode.GW, Currency.XOF),
    GUYANA (CountryCode.GY, Currency.GYD),
    HAITI (CountryCode.HT, Currency.HTG),
    HONDURAS (CountryCode.HN, Currency.HNL),
    HONG_KONG (CountryCode.HK, Currency.HKD),
    HUNGARY (CountryCode.HU, Currency.HUF),
    ICELAND (CountryCode.IS, Currency.ISK),
    INDIA (CountryCode.IN, Currency.INR),
    INDONESIA (CountryCode.ID, Currency.IDR),
    IRAN (CountryCode.IR, Currency.IRR),
    IRAQ (CountryCode.IQ, Currency.IQD),
    IRELAND (CountryCode.IE, Currency.EUR),
    ISRAEL (CountryCode.IL, Currency.ILS),
    ITALY (CountryCode.IT, Currency.EUR),
    JAMAICA (CountryCode.JM, Currency.JMD),
    JAPAN (CountryCode.JP, Currency.JPY),
    JORDAN (CountryCode.JO, Currency.JOD),
    KAZAKHSTAN (CountryCode.KZ, Currency.KZT),
    KENYA (CountryCode.KE, Currency.KES),
    KIRIBATI (CountryCode.KI, Currency.AUD),
    KUWAIT (CountryCode.KW, Currency.KWD),
    KYRGYZSTAN (CountryCode.KG, Currency.KGS),
    LATVIA (CountryCode.LV, Currency.LVL),
    LEBANON (CountryCode.LB, Currency.LBP),
    LIBERIA (CountryCode.LR, Currency.LRD),
    LIECHTENSTEIN (CountryCode.LI, Currency.CHF),
    LITHUANIA (CountryCode.LT, Currency.LTL),
    LUXEMBOURG (CountryCode.LU, Currency.EUR),
    MACAO (CountryCode.MO, Currency.MOP),
    MALAWI (CountryCode.MW, Currency.MWK),
    MALAYSIA (CountryCode.MY, Currency.MYR),
    MALDIVES (CountryCode.MV, Currency.MVR),
    MALI (CountryCode.ML, Currency.XOF),
    MALTA (CountryCode.MT, Currency.MTL),
    MARSHALL_ISLANDS (CountryCode.MH, Currency.USD),
    MARTINIQUE (CountryCode.MQ, Currency.EUR),
    MAURITANIA (CountryCode.MR, Currency.MRO),
    MAURITIUS (CountryCode.MU, Currency.MUR),
    MAYOTTE (CountryCode.YT, Currency.EUR),
    MEXICO (CountryCode.MX, Currency.MXN),
    MICRONESIA_FEDERATED_STATES_OF	(CountryCode.FM, Currency.USD),
    MONACO (CountryCode.MC, Currency.EUR),
    MONGOLIA (CountryCode.MN, Currency.MNT),
    MONTSERRAT (CountryCode.MS, Currency.XCD),
    MOROCCO (CountryCode.MA, Currency.MAD),
    MOZAMBIQUE (CountryCode.MZ, Currency.MZM),
    MYANMAR (CountryCode.MM, Currency.MMK),
    NAMIBIA (CountryCode.NA, Currency.ZAR),
    NAURU (CountryCode.NR, Currency.AUD),
    NEPAL (CountryCode.NP, Currency.NPR),
    NETHERLANDS (CountryCode.NL, Currency.EUR),
    NEW_CALEDONIA (CountryCode.NC, Currency.XPF),
    NEW_ZEALAND (CountryCode.NZ, Currency.NZD),
    NICARAGUA (CountryCode.NI, Currency.NIO),
    NIGER (CountryCode.NE, Currency.XOF),
    NIGERIA (CountryCode.NG, Currency.NGN),
    NIUE (CountryCode.NU, Currency.NZD),
    NORFOLK_ISLAND (CountryCode.NF, Currency.AUD),
    NORTHERN_MARIANA_ISLANDS (CountryCode.MP, Currency.USD),
    NORWAY (CountryCode.NO, Currency.NOK),
    OMAN (CountryCode.OM, Currency.OMR),
    PAKISTAN (CountryCode.PK, Currency.PKR),
    PALAU (CountryCode.PW, Currency.USD),
    PANAMA (CountryCode.PA, Currency.PAB),
    PAPUA_NEW_GUINEA (CountryCode.PG, Currency.PGK),
    PARAGUAY (CountryCode.PY, Currency.PYG),
    PERU (CountryCode.PE, Currency.PEN),
    PHILIPPINES (CountryCode.PH, Currency.PHP),
    PITCAIRN (CountryCode.PN, Currency.NZD),
    POLAND (CountryCode.PL, Currency.PLN),
    PORTUGAL (CountryCode.PT, Currency.EUR),
    PUERTO_RICO (CountryCode.PR, Currency.USD),
    QATAR (CountryCode.QA, Currency.QAR),
    REUNION (CountryCode.RE, Currency.EUR),
    ROMANIA (CountryCode.RO, Currency.ROL),
    RWANDA (CountryCode.RW, Currency.RWF),
    SAINT_HELENA (CountryCode.SH, Currency.SHP),
    SAINT_KITTS_AND_NEVIS (CountryCode.KN, Currency.XCD),
    SAINT_LUCIA (CountryCode.LC, Currency.XCD),
    SAINT_PIERRE_AND_MIQUELON (CountryCode.PM, Currency.EUR),
    SAINT_VINCENT_AND_THE_GRENADINES (CountryCode.VC, Currency.XCD),
    SAMOA (CountryCode.WS, Currency.WST),
    SAN_MARINO (CountryCode.SM, Currency.EUR),
    SAO_TOME_AND_PRINCIPE (CountryCode.ST, Currency.STD),
    SAUDI_ARABIA (CountryCode.SA, Currency.SAR),
    SENEGAL (CountryCode.SN, Currency.XOF),
    SEYCHELLES (CountryCode.SC, Currency.SCR),
    SIERRA_LEONE (CountryCode.SL, Currency.SLL),
    SINGAPORE (CountryCode.SG, Currency.SGD),
    SLOVAKIA (CountryCode.SK, Currency.SKK),
    SLOVENIA (CountryCode.SI, Currency.SIT),
    SOLOMON_ISLANDS (CountryCode.SB, Currency.SBD),
    SOMALIA (CountryCode.SO, Currency.SOS),
    SOUTH_AFRICA (CountryCode.ZA, Currency.ZAR),
    SPAIN (CountryCode.ES, Currency.EUR),
    SRI_LANKA (CountryCode.LK, Currency.LKR),
    SUDAN (CountryCode.SD, Currency.SDD),
    SURINAME (CountryCode.SR, Currency.SRD),
    SVALBARD_AND_JAN_MAYEN (CountryCode.SJ, Currency.NOK),
    SWAZILAND (CountryCode.SZ, Currency.SZL),
    SWEDEN (CountryCode.SE, Currency.SEK),
    SWITZERLAND (CountryCode.CH, Currency.CHF),
    SYRIAN_ARAB_REPUBLIC (CountryCode.SY, Currency.SYP),
    TAIWAN (CountryCode.TW, Currency.TWD),
    TAJIKISTAN (CountryCode.TJ, Currency.TJS),
    TANZANIA (CountryCode.TZ, Currency.TZS),
    THAILAND (CountryCode.TH, Currency.THB),
    TIMOR_LESTE	(CountryCode.TL, Currency.USD),
    TOGO (CountryCode.TG, Currency.XOF),
    TOKELAU (CountryCode.TK, Currency.NZD),
    TONGA (CountryCode.TO, Currency.TOP),
    TRINIDAD_AND_TOBAGO (CountryCode.TT, Currency.TTD),
    TUNISIA (CountryCode.TN, Currency.TND),
    TURKEY (CountryCode.TR, Currency.TRL),
    TURKMENISTAN (CountryCode.TM, Currency.TMM),
    TURKS_AND_CAICOS_ISLANDS (CountryCode.TC, Currency.USD),
    TUVALU (CountryCode.TV, Currency.AUD),
    UGANDA (CountryCode.UG, Currency.UGX),
    UKRAINE (CountryCode.UA, Currency.UAH),
    UNITED_ARAB_EMIRATES (CountryCode.AE, Currency.AED),
    UNITED_KINGDOM (CountryCode.GB, Currency.GBP),
    UNITED_STATES (CountryCode.US, Currency.USD),
    URUGUAY (CountryCode.UY, Currency.UYU),
    UZBEKISTAN (CountryCode.UZ, Currency.UZS),
    VANUATU (CountryCode.VU, Currency.VUV),
    VENEZUELA (CountryCode.VE, Currency.VEB),
    VIET_NAM (CountryCode.VN, Currency.VND),
    WALLIS_AND_FUTUNA (CountryCode.WF, Currency.XPF),
    WESTERN_SAHARA (CountryCode.EH, Currency.MAD),
    YEMEN (CountryCode.YE, Currency.YER),
    ZAMBIA (CountryCode.ZM, Currency.ZMK),
    ZIMBABWE (CountryCode.ZW, Currency.ZWD)
}